### PR TITLE
Minor bugfixes in run().

### PR DESCRIPTION
**Pull request by kpbuvic**

### CODE REVIEW

**Comment by kpbuvic** [comment]
I'm not used to using Github for collaborative programming. I hope I did the pull request right.

**Comment by tonydavis629** [comment]
Thanks!

**Comment by kpbuvic** [comment]
Hi Tony,

I thought I'd pass some information along to you in the hopes that you can
make use of it.

I work for Ocean Networks Canada (ONC). We bought our Splashdrone to
perform radar calibrations (known as Antenna Pattern Measurements, or
APMs). I put in a fair bit of work to create a python class
"Apm_Splashdrone" that subclassed your splashdrone.py. Your code had
waypoints hard-coded in, and I wanted a program that could read in files
created by the Ardupilot Mission Planner program (we have many radars, so
hard-coded waypoints weren't practical).

My efforts were successful. I got the code to the point where I could
create an arbitrary mission file in Mission Planner, then read it into my
python code, which would then write the mission to the vehicle, and execute
it.

Unfortunately, we discovered that while my code was reliable, the drone
itself was not. In autonomous flight, it intermittently and unpredictably
would hover in place, or dance around the sky, or return home. We have
abandoned the use of the Splashdrone in favour of a different brand of
quadcopter, which is proving more reliable for autonomous work.

So I have all this code that I put a lot of effort into that is now useless
for us. I've made it available for downloading at
https://drive.google.com/drive/folders/1Bip5tE-Bb2RotRdpql2UGwef7WOWOS_S?usp=sharing.
If you want to incorporate it into your own drone software, please do so.
It would make me happy to think that all my work wasn't wasted.

I have attached a pdf of the readme file I created for our own use here at
ONC; reading it should give you an idea of whether it makes sense to try to
adapt my code for your use.

Thanks again for the package you created and for all your help.

Cheers,
Kevin

**Comment by tonydavis629** [comment]
Thanks for reaching out, I'm glad you found the code useful. Yeah we had
the same experience with the splashdrone, it is cheap hardware. I would be
happy to merge your changes if you submit a pull request, I'm not currently
maintaining the HAUCS repo :)

Tony Davis
+1 305 619 1239

**Comment by kpbuvic** [comment]
Hi Tony,

If you're not maintaining the repo, I don't think I'll bother making a pull
request. It sounds like the Splashdrone API is a bit of a dead end for
autonomous missions anyway.

We were actually really impressed with the Splashdrone hardware. I'm hoping
someone will take on the task of fitting an Ardupilot controller to one to
get the best of both worlds: a waterproof quadcopter that actually follows
commands!

Good luck with your flying,
Kevin

**Comment by tonydavis629** [comment]
Fair enough. Yeah agreed about the ardupilot. I'm hoping to one day get
around to making an open source 3d printed water proof housing to make that
possible.

**Comment by kpbuvic** [comment]
Let me know if you ever do. We might be your first customer!

Cheers,
Kevin

**Pull request merged**
